[tool.poetry]
name = "aoc-24"
version = "0.1.0"
description = ""
authors = ["itxasos23 <txas@txas.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.14.0"
icecream = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
